### ISSUE TITLE
Unity上でのパーティクルの無限生成について

### ISSUE THREAD

**Issue by Ryoht** [SpriteStudio/SSPlayerForUnity#19]
現在SS5Player1.4.3、SpriteStudio5.7.0を使用し、スプライトスタジオ側でパーティクルを無限生成に設定したデータをUnityにインポートしましたが、Unity上ではパーティクルが無限生成されません。
これはUnity上では無限生成できない仕様なのでしょうか？それとも何か特別な設定があるのでしょうか？

よろしくお願いいたします。

**Comment by DKAlpha** [comment]
こちらは旧SSPlayerとなります。パーティクル機能についてはサポートしておりません。
SS5Playerの方に投稿いただいているようですので、こちらの問い合わせはクローズとさせていただきます。
